// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJcMErKSQUkxIXBZAT3-tochiFH8K3Pak',
    appId: '1:73787427967:web:ef86dbdec3e143f3a9c34a',
    messagingSenderId: '73787427967',
    projectId: 'project1-54a55',
    authDomain: 'project1-54a55.firebaseapp.com',
    storageBucket: 'project1-54a55.appspot.com',
    measurementId: 'G-61P5HJ3EK8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDR9swDBVjbVqeiiR0cWRYedQig05L7zUA',
    appId: '1:73787427967:android:b399a1d311fa0b70a9c34a',
    messagingSenderId: '73787427967',
    projectId: 'project1-54a55',
    storageBucket: 'project1-54a55.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCz87FRvIC4EXaSV8okf5IZ_ttp-zb9D90',
    appId: '1:73787427967:ios:63fe4948a2791e15a9c34a',
    messagingSenderId: '73787427967',
    projectId: 'project1-54a55',
    storageBucket: 'project1-54a55.appspot.com',
    iosBundleId: 'com.example.flutterlist',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCz87FRvIC4EXaSV8okf5IZ_ttp-zb9D90',
    appId: '1:73787427967:ios:63fe4948a2791e15a9c34a',
    messagingSenderId: '73787427967',
    projectId: 'project1-54a55',
    storageBucket: 'project1-54a55.appspot.com',
    iosBundleId: 'com.example.flutterlist',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAJcMErKSQUkxIXBZAT3-tochiFH8K3Pak',
    appId: '1:73787427967:web:f8a043e0a9776895a9c34a',
    messagingSenderId: '73787427967',
    projectId: 'project1-54a55',
    authDomain: 'project1-54a55.firebaseapp.com',
    storageBucket: 'project1-54a55.appspot.com',
    measurementId: 'G-4CN1MJ6HRY',
  );

}